---
- hosts: local
  become: true
  connection: local
  user: vagrant
  tasks:
    - name: install middlewares
      become: True
      yum: name={{ item }} state=latest
      with_items:
        - "@Development tools"
        - git
        - yum-plugin-changelog
        - vim-enhanced

    - name: Set JST timezone
      become: True
      file: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link force=yes
